dependencies:
  - name: template-node-react
    version: 1.0.0-2
    repository: http://artifactory.garage-devtools-sfo-rhos.us-east.containers.appdomain.cloud/artifactory/generic-local/garage-devtools-sfo/
